#We need to keep this file for Morning Glory

development:
  access_key_id: AKIAICNJ2E4FNFFDNJEQ
  secret_access_key: 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
  bucket: cmusv-rails-development

test:
  access_key_id: AKIAICNJ2E4FNFFDNJEQ
  secret_access_key: 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
  bucket: cmusv-rails-test

production:
  access_key_id: AKIAI2XCP5WS42BW4F6A
  secret_access_key: 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
  bucket: cmusv-rails-production



  # modify ~/.bashrc
#  export S3_KEY=AKIAICNJ2E4FNFFDNJEQ
#  export S3_SECRET=n5RB9/gb4oJsbM6OBmlO0jXI0MaoXhjHYGI/y+sPM
#  export S3_BUCKET = cmusv-rails-development


  # heroku config:add S3_KEY=AKIAJ22P7FS6FGJHD7YA S3_SECRET=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 S3_BUCKET=cmusv-rails-production
