development:
  username: team.deming@sandbox.sv.cmu.edu
  password: MfSE@sv
  google_domain: sandbox.sv.cmu.edu

test:
  username: team.deming@sandbox.sv.cmu.edu
  password: MfSE@sv
  google_domain: sandbox.sv.cmu.edu


consumer_key: JUbt0bVxzf7WSbMvHACAA

Yammmer ----

OAuth details for RailsApp

Consumer (Application) Key
    JUbt0bVxzf7WSbMvHACAA
Consumer (Application) Secret
    kZ8UzOCw3A3Fu696XU1lZWwoLvzgsHzTrAs5CRrxfo
Request Token URL
    https://www.yammer.com/oauth/request_token
Access Token URL
    https://www.yammer.com/oauth/access_token
Authorize URL
    https://www.yammer.com/oauth/access_token

We support plain text (recommended) as well as HMAC-SHA1. Only SSL requests are allowed.